{
 "title": "Coin Details",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Databases",
    "query": "ethereum,coins,cardano,zcash,chainlink,polkadot,stellar,algorand,ampleforth,zilliqa,vechain,bitcoin_diamond,litecoin,compound_ether,compound_coin,waves,uma,bzx_protocol,band_protocol"
   }
  ]
 },
 "panels": [
  {
   "title": "Currently Available Bitcoins",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  market_cap_eur / price_eur AS \"Currently Available Bitcoins\",\n  (21000000 - (market_cap_eur / price_eur)) AS \"Remaining\"\nFROM coins\norder by time_stamp asc"
    }
   ]
  },
  {
   "title": "Alexa Page Rank",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  public_alexa_rank\nFROM \"$Databases\"\nwhere public_alexa_rank > 0\norder by time_stamp asc"
    }
   ]
  },
  {
   "title": "Currently Available $Databases Coins",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  market_cap_eur / price_eur\nFROM \"$Databases\"\norder by time_stamp asc"
    }
   ]
  },
  {
   "title": "Current Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select\n  time_stamp as \"time\",\n  price_eur as \"$Databases eur\",\n  price_usd as \"$Databases usd\"\nfrom \"$Databases\"\norder by time_stamp asc"
    }
   ]
  },
  {
   "title": "Current Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select\n  time_stamp as \"time\",\n  market_cap_eur as \"cap $Databases eur\",\n  market_cap_usd as \"cap $Databases usd\"\nfrom \"$Databases\"\norder by time_stamp asc"
    }
   ]
  },
  {
   "title": "Price Chart",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  price_eur\nFROM \"$Databases\"\norder by time_stamp asc"
    }
   ]
  },
  {
   "title": "Market Cap EUR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  market_cap_eur\nFROM \"$Databases\"\nORDER BY time_stamp desc"
    }
   ]
  },
  {
   "title": "# of Available Coins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  market_cap_eur / price_eur AS \"Available Coins\"\nFROM \"$Databases\"\nORDER BY time_stamp asc"
    }
   ]
  },
  {
   "title": "Social Media Analytics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  reddit_subscribers,\n  twitter_followers,\n  dev_forks,\n  reddit_avg_posts_48_hours\nFROM \"$Databases\"\nwhere reddit_subscribers > 0 and twitter_followers > 0 and dev_forks > 0 and reddit_avg_posts_48_hours > 0\nORDER BY time_stamp asc"
    }
   ]
  },
  {
   "title": " % Reddit Subscribers comparison To Big Coins",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select cast(reddit_subscribers as decimal) / (select reddit_subscribers\nfrom coins\nwhere time_stamp = (select max(time_stamp)\nfrom coins\nwhere reddit_subscribers > 0)) as percent_to_bitcoin, time_stamp as \"time\"\nfrom \"$Databases\"\nwhere reddit_subscribers > 0\norder by time_stamp asc"
    }
   ]
  },
  {
   "title": "Reddit Subscribers comparison To Big Coins",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  reddit_subscribers as \"$Databases reddit_subscribers\"\nFROM \"$Databases\"\nwhere reddit_subscribers > 0\nORDER BY time_stamp asc"
    },
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  reddit_subscribers as \"Bitcoin reddit_subscribers\"\nFROM coins\nwhere reddit_subscribers > 0\nORDER BY time_stamp asc"
    },
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  reddit_subscribers as \"Ethereum reddit_subscribers\"\nFROM ethereum\nwhere reddit_subscribers > 0\nORDER BY time_stamp asc"
    }
   ]
  },
  {
   "title": "Twitter Subscribers comparison To Big Coins",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  twitter_followers as \"$Databases twitter_followers\"\nFROM \"$Databases\"\nwhere twitter_followers > 0\nORDER BY time_stamp asc"
    },
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  twitter_followers as \"$Databases twitter_followers\"\nFROM coins\nwhere twitter_followers > 0\nORDER BY time_stamp asc"
    },
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  twitter_followers as \"Ethereum twitter_followers\"\nFROM ethereum\nwhere twitter_followers > 0\nORDER BY time_stamp asc"
    }
   ]
  },
  {
   "title": "Commit Count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  dev_commit_count_4_weeks AS \"commits\"\nFROM \"$Databases\"\nwhere dev_commit_count_4_weeks > 0\norder by time_stamp asc"
    }
   ]
  },
  {
   "title": "Dev Stats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  dev_forks,\n  dev_stars,\n  dev_total_issues,\n  dev_closed_issues\nFROM \"$Databases\"\nwhere dev_forks > 0 and dev_stars > 0 and dev_total_issues > 0 and dev_closed_issues > 0\nORDER BY time_stamp desc"
    }
   ]
  },
  {
   "title": "Approx. Growth Available Bitcoins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time_stamp AS \"time\",\r\n    30084510 + (14490340 - 30084510)/(1 + ((row_number() OVER(order by time_stamp))/6619.766)^0.8395173) as \"Approximate Function of Available Bitcoins\"\r\n  FROM coins"
    },
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  market_cap_eur / price_eur AS \"Available Bitcoins\"\nFROM coins\nORDER BY time_stamp asc"
    }
   ]
  },
  {
   "title": "Growth Rate Approximated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time_stamp AS \"time\",\r\n    2.11181 * 10^10 /((((row_number() OVER(order by time_stamp))^0.839517 + 1613.11)^2) * ((row_number() OVER(order by time_stamp))^0.160483)) as \"Growth Rate Approx Function\"\r\n  FROM coins"
    }
   ]
  }
 ]
}