{
 "title": "Table View",
 "time": { "from": "2015-08-08T00:00:00.000Z", "to": "2020-09-04T02:19:47.000Z" },
 "templating": {
  "list": [
   {
    "name": "Coin",
    "query": "ethereum,coins,cardano,zcash,chainlink,polkadot,stellar,algorand,ampleforth,zilliqa,vechain,bitcoin_diamond,litecoin,compound_ether,compound_coin,waves,uma,bzx_protocol,band_protocol,ocean_protocol,singularitynet,theta_token,thorchain,kava"
   },
   {
    "name": "DeltaDifference",
    "query": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,30,35,40,45,50,55,60,65,70,75,80,90,100,110,120"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Price",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp as \"time\",\n  price_eur as \"Price EUR_____\",\n  price_usd as \"Price USD_____\",\n  market_cap_eur as \"Market CAP EUR_____\",\n  market_cap_eur as \"Market CAP USD_____ \"\nFROM\n  \"$Coin\"\nORDER BY time_stamp asc\n"
    }
   ]
  },
  {
   "title": "Old Price",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select time,\n\"$Coin eurb\" as \"Old Price EUR\",\n\"$Coin usdb\" as \"Old Price USD\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  price_usd as \"$Coin usdb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur,price_usd\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone\nORDER BY countertwo ASC"
    }
   ]
  },
  {
   "title": "Delta",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"EUR Entry Delta\",\n\"$Coin usd\" - \"$Coin usdb\" as \"USD Entry Delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  price_usd as \"$Coin usd\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur,price_usd\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  price_usd as \"$Coin usdb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur,price_usd\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone\nORDER BY countertwo ASC"
    }
   ]
  },
  {
   "title": "Diff between Now and Compare Date",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select \nage(time,timeb) as \"Compare Age Diff timestamp\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone\nWHERE counter = 1"
    }
   ]
  },
  {
   "title": "Price Delta EUR",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"$DeltaDifference Entry Delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone\nORDER BY countertwo ASC"
    },
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"2 Entry Delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) -  2) as \"countertwobtwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobtwo\nORDER BY countertwo ASC"
    },
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"3 Entry Delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - 3) as \"countertwobthree\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobthree\nORDER BY countertwo ASC"
    },
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"4 Entry Delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - 4) as \"countertwobfour\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobfour\nORDER BY countertwo ASC"
    },
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"5 Entry Delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - 5) as \"countertwobfive\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobfive\nORDER BY countertwo ASC"
    },
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"7 Entry Delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - 7) as \"countertwobseven\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobseven\nORDER BY countertwo ASC"
    }
   ]
  },
  {
   "title": "Compare Delta",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "select \n\"countertwo\" as \"Entry #\",\ntime as \"actual time\",\ntimeb as \"compare time\",\n\"$Coin eur\" as \"Price $Coin\",\n\"$Coin eurb\" as \"Price Delta Diff Entry $Coin\",\n\"$Coin eur\" - \"$Coin eurb\" as \"$DeltaDifference Entry Delta\",\nage(time,timeb) as \"Compare Age Diff timestamp\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone"
    }
   ]
  },
  {
   "title": "Price Performance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc"
    }
   ]
  },
  {
   "title": "Delta to Delta Diff Entry",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"$DeltaDifference Entry Delta\",\n\"$Coin eur\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone"
    }
   ]
  },
  {
   "title": "Price EUR",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  time_stamp::date as \"date\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\",\n  (to_char(current_date,'yyyymmdd')::bigint - (row_number() OVER(order by time_stamp desc))) as \"deltadate\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp Desc"
    }
   ]
  }
 ]
}