{
 "title": "Price Update",
 "time": { "from": "2015-08-07T00:00:00.000Z", "to": "2020-09-09T01:27:55.000Z" },
 "templating": {
  "list": [
   {
    "name": "Coin",
    "query": "ethereum,coins,cardano,zcash,chainlink,polkadot,stellar,algorand,ampleforth,zilliqa,vechain,bitcoin_diamond,litecoin,compound_ether,compound_coin,waves,uma,bzx_protocol,band_protocol,ocean_protocol,singularitynet,theta_token,thorchain,kava"
   },
   {
    "name": "CompareDate",
    "query": "select \ntimeb as comparetime\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone\norder by counter asc"
   },
   {
    "name": "DeltaDifference",
    "query": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,30,35,40,45,50,55,60,65,70,75,80,90,100,110,120"
   }
  ]
 },
 "panels": [
  {
   "title": "Comparison Age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \nage(time,timeb)\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - counternumber+1) as \"countertwobone\"\n\n\n\nfrom (select time_stamp,price_eur,price_usd,market_cap_eur,(select counternumber from (select time_stamp, (row_number() OVER(order by time_stamp desc)) as \"counternumber\" from \"$Coin\" group by time_stamp) as qry where time_stamp = '$CompareDate') from $Coin) as values\n\n\n\ngroup by time_stamp,price_eur,market_cap_eur,counternumber\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone\nWHERE counter = 1"
    }
   ]
  },
  {
   "title": "Current Price",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (select max(time_stamp) from $Coin) as \"Latest Price from\",\n  price_eur as \"EUR:\",\n  price_usd as \"USD:\"\nFROM\n  \"$Coin\"\nORDER BY time_stamp asc\n"
    }
   ]
  },
  {
   "title": "Price Delta %",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select \n((\"$Coin eur\"/\"$Coin eurb\")-1)*100 as \"EUR Entry Delta %\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  price_usd as \"$Coin usd\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur,price_usd\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  price_usd as \"$Coin usdb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - counternumber+1) as \"countertwobone\"\n\nfrom (select time_stamp,price_eur,price_usd,market_cap_eur,(select counternumber from (select time_stamp, (row_number() OVER(order by time_stamp desc)) as \"counternumber\" from \"$Coin\" group by time_stamp) as qry where time_stamp = '$CompareDate') from $Coin) as values\n\ngroup by time_stamp,price_eur,market_cap_eur,price_usd,counternumber\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone\nORDER BY countertwo ASC"
    }
   ]
  },
  {
   "title": "Price Delta",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select \"$Coin eur\" - \"$Coin eurb\" as \"EUR Entry Delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  price_usd as \"$Coin usd\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur,price_usd\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  price_usd as \"$Coin usdb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - counternumber+1) as \"countertwobone\"\n\nfrom (select time_stamp,price_eur,price_usd,market_cap_eur,(select counternumber from (select time_stamp, (row_number() OVER(order by time_stamp desc)) as \"counternumber\" from \"$Coin\" group by time_stamp) as qry where time_stamp = '$CompareDate') from $Coin) as values\n\ngroup by time_stamp,price_eur,market_cap_eur,price_usd,counternumber\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone\nORDER BY countertwo ASC"
    }
   ]
  },
  {
   "title": "Compare Historical Price",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select\n(select distinct time_stamp from $Coin where time_stamp = '$$CompareDate') as \"Compare Values from: \",\n\"$Coin eurb\" as \"EUR:\",\n\"$Coin usdb\" as \"USD:\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  price_usd as \"$Coin usdb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - counternumber+1) as \"countertwobone\"\n\nfrom (select time_stamp,price_eur,price_usd,market_cap_eur,(select counternumber from (select time_stamp, (row_number() OVER(order by time_stamp desc)) as \"counternumber\" from \"$Coin\" group by time_stamp) as qry where time_stamp = '$CompareDate') from $Coin) as values\n\n\ngroup by time_stamp,price_eur,market_cap_eur,price_usd,counternumber\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone\nORDER BY countertwo ASC"
    }
   ]
  },
  {
   "title": "Delta by CompareDate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"EUR Entry Delta\",\n((\"$Coin eur\"/\"$Coin eurb\")-1)*100 as \"EUR Entry Delta %\",\n\"$Coin usd\" - \"$Coin usdb\" as \"USD Entry Delta\",\n((\"$Coin usd\"/\"$Coin usdb\")-1)*100 as \"USD Entry Delta %\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  price_usd as \"$Coin usd\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur,price_usd\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  price_usd as \"$Coin usdb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - counternumber+1) as \"countertwobone\"\n\nfrom (select time_stamp,price_eur,price_usd,market_cap_eur,(select counternumber from (select time_stamp, (row_number() OVER(order by time_stamp desc)) as \"counternumber\" from \"$Coin\" group by time_stamp) as qry where time_stamp = '$CompareDate') from $Coin) as values\n\ngroup by time_stamp,price_eur,market_cap_eur,price_usd,counternumber\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone\nORDER BY countertwo ASC"
    }
   ]
  },
  {
   "title": "Up Down Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select cast(ups as decimal) / downs as \"Up / Down Ratio\", ups, downs, ups+downs as \"total datapoints\", upssum as \"total up value\", downssum as \"total down value\", upssum + downssum as \"Total Balance\"\nfrom\n(select (select count(delta) as ups\nfrom (select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone) as deltatable\nwhere time > '$CompareDate' and delta >= 0),\n\n\n(select sum(delta) as upssum\nfrom (select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone) as deltatable\nwhere time > '$CompareDate' and delta >= 0),\n\n\n\n\n\n\n\n(select count(delta) as downs\nfrom (select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone) as deltatable\nwhere time > '$CompareDate' and delta < 0),\n\n(select sum(delta) as downssum\nfrom (select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone) as deltatable\nwhere time > '$CompareDate' and delta < 0)\n\n\n\n) as updowntable"
    }
   ]
  },
  {
   "title": "Price Chart",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time_stamp as time, price_eur\nfrom $Coin\norder by time_stamp asc"
    }
   ]
  },
  {
   "title": "Delta Difference",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"Compare Date = $CompareDate Entry Delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - counternumber+1) as \"countertwobone\"\nfrom (select time_stamp,price_eur,price_usd,market_cap_eur,(select counternumber from (select time_stamp, (row_number() OVER(order by time_stamp desc)) as \"counternumber\" from \"$Coin\" group by time_stamp) as qry where time_stamp = '$CompareDate') from $Coin) as values\ngroup by time_stamp,price_eur,market_cap_eur,counternumber\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone"
    },
    {
     "rawSql": "select time,\n\"$Coin eur\" - \"$Coin eurb\" as \"DeltaDifference = $DeltaDifference Entry Delta\"\nFrom(select\n  time_stamp as \"time\",\n  price_eur as \"$Coin eur\",\n  market_cap_eur as \"$Coin market cap eur\",\n  market_cap_eur / price_eur as \"$Coin # of coins\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entry\",\n  (row_number() OVER(order by time_stamp desc)) as \"counter\",\n  (row_number() OVER(order by time_stamp desc) - 1) as \"countertwo\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableA\nINNER JOIN (select\n  time_stamp as \"timeb\",\n  price_eur as \"$Coin eurb\",\n  market_cap_eur as \"$Coin market cap eurb\",\n  market_cap_eur / price_eur as \"$Coin # of coinsb\",\n  (row_number() OVER(order by time_stamp)) as \"# Database Entryb\",\n  (row_number() OVER(order by time_stamp desc)) as \"counterb\",\n  (row_number() OVER(order by time_stamp desc) - $DeltaDifference) as \"countertwobone\"\nfrom \"$Coin\"\ngroup by time_stamp,price_eur,market_cap_eur\norder by time_stamp asc) AS derivedTableB\nON counter = countertwobone"
    }
   ]
  }
 ]
}