app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/cryptobackup
    username: postgres
    password: password
    pool-size: 30

spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:password@localhost:27017/coin_candles?authSource=admin