app:
  datasource:
    jdbc-url: ${CRYPTO_API_DB_URL:jdbc:postgresql://localhost:5432/coin}
    username: ${CRYPTO_API_DB_USERNAME:postgres}
    password: ${CRYPTO_API_DB_PASSWORD:password}
    pool-size: 30

springdoc:
  swagger-ui:
    path: /api-docs

spring:
  profiles:
    active: dev